# site settings
title: TVSunnah Podcast
#subtitle: by TVSunnah
email: youremailaddress@gmail.com
description: If you’re new to TVSunnah Podcast, we’ve got a lot of podcasts for you!
baseurl: "/tvsunnah-podcast"
#baseurl: ""
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/TVSunnah-191028304267964/
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/tvsunnahproductions/
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/tvsunnah/
youtube_url: https://www.youtube.com/user/TVSUNNAH/

# build settings
#permalink: /:categories/:title/
markdown: kramdown

sass:
  style: compressed

# ------------------------------------------------------------------------
# RSS Settings

rss_path: /feed
rss_name: index.xml
rss_post_limit: 10

# Podcast General Settings
# ------------------------------------------------------------------------

# The homepage of your podcast
podcast_url: http://www.joebuhlig.com/whaddyaknowjoe
podcast_album_art: /assets/base/Whaddya-Know-Joe-Album-Art.png
podcast_title: Whaddya Know Joe?
podcast_owner: Joe Buhlig
podcast_email: joe@joebuhlig.com
podcast_category: Technology
podcast_subcategory_one: Software How-To
podcast_subcategory_two: Gadgets
podcast_explicit: "no"
podcast_author: Joe Buhlig
podcast_description: Productivity stories from the trenches. What works and what I'll never do again. Hosted by Joe Buhlig.
podcast_summary: Joe Buhlig walks you through real life story and then breaks down the productivity tools and techniques used. It's a great way to learn how to implement the tips and tricks that you see across the web. Productivity stories from the trenches. What works and what to never try.
podcast_subtitle: Productivity stories from the trenches. What works and what I'll never do again. Hosted by Joe Buhlig.
