# site settings
title: TVSunnah Podcast
#subtitle: by TVSunnah
email: contact@tvsunnahpodcast.com
description: If you’re new to TVSunnah Podcast, we’ve got a lot of podcasts for you!
keyword: podcast, tvsunnah, tvsunnah podcast, islamic podcast, islam, sunnah, religion, education, ahli sunnah wal jamaah
baseurl: ""
url: "https://www.tvsunnahpodcast.com"
author:
street_address: 42 Jalan SS12/1F
city: Subang Jaya
state: Selangor
zip_code: 47500
country: Malaysia
phone: +6012 3076703

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/TVSunnah-191028304267964/
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/tvsunnahproductions/
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/tvsunnah/
youtube_url: https://www.youtube.com/user/TVSUNNAH/

# build settings
#permalink: /:categories/:title/
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-sitemap

# ------------------------------------------------------------------------
# RSS Settings

rss_path: /feed
rss_name: index.xml
rss_post_limit: 10

# Podcast General Settings
# ------------------------------------------------------------------------

# The homepage of your podcast
podcast_owner: TVSunnah Podcast
podcast_email: contact@tvsunnahpodcast.com
podcast_category: Religion &amp; Spirituality
podcast_subcategory_one: Islam
podcast_subcategory_two: Spirituality
podcast_explicit: "no"
